//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО_Спортивные_товары.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int OrderId { get; set; }
        public string ProductArtideNumber { get; set; }
        public Nullable<int> ProductCount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
